# Define the compiler
CC=gcc

# Define any compile-time flags
CFLAGS=-Wall -ansi -pedantic

# Define the target executable name
TARGET=output

# Define source files
SRC=my_add.c

# Default target
all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)
